name: CI

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # -- Deno ----------------------------------------------------------
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Deno format check
        run: deno fmt --check src/ test/
      - name: Deno lint
        run: deno lint src/ test/

      # ---- Node + pnpm --------------------------------------------------
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      # -- Build / type-check / tests -----------------------------------
      - name: TypeScript type-check
        run: pnpm exec tsc --noEmit
      - name: Build library
        run: pnpm build
      - name: Run tests
        run: pnpm test

      # -- Re-use artefacts in publish ----------------------------------
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --filter . --no-git-checks --access public

